image: "python:3.8"
stages:
  - test
#  - deploy
  - build

#before_script:
#  - env
#  - apt-get update && apt-get upgrade -y
#  - apt-get install zip -y
#  - python --version
#  - which python
#  - pip3 install awscli

test:
  stage: test
  script:
    - python -m pip install --upgrade pip
    - pip install flake8 pytest
    - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - pip install .
    - pip install moto
    - export PYTHONPATH=$(pwd)
    - python tests/newport_helpers/cfn_helpers.py
    - python tests/newport_helpers/helpers.py
build:
  stage: build
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  script:
#    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#    - docker build -t $CI_REGISTRY/group/project/image:latest .
#    - docker push $CI_REGISTRY/group/project/image:latest
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/image:latest .
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/image:latest
#deploy:
#  stage: deploy
#  script:
#    - apt-get update && apt-get upgrade -y
#    - apt-get install zip -y
#    - zip -r source.zip .
#    - pip3 install awscli
#    - aws s3 cp source.zip s3://${S3_BUCKET}/source/newport_helpers.zip

#rubocop:
#  script:
#    - bundle exec rubocop
